### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by LouisJS** [appcues/appcues-react-native-module#126]
Hi,

My setup is 

| Setup  | Version |
| ------------- | ------------- |
| React Native  | 0.68.2  |
| AppCues  |  3.1.4  |
| XCode | 13.4.1 |

I'm facing an issue when building my app

```
Undefined symbols for architecture arm64:
  "tooltipFrame #1 (position: AppcuesKit.ContentPosition) -> __C.CGRect in AppcuesKit.TooltipWrapperView.(tooltipPosition in _55E48D59DE4D8313706070264B9F9B2C)(for: __C.CGRect) -> __C.CGRect", referenced from:
      AppcuesKit.TooltipWrapperView.(tooltipPosition in _55E48D59DE4D8313706070264B9F9B2C)(for: __C.CGRect) -> __C.CGRect in libAppcues.a(TooltipWrapperView.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm available for any further informations if needed

**Comment by iujames** [comment]
On the Android side, our native SDK (which this React Native module wraps) does require Android API 34 in the latest versions, due to the usage of Jetpack Compose 1.5. This ends up causing the latest versions of this module to also require Android API 34 in the build, and thus a compatible version of React Native. I believe the root issue on the React Native side with Android API 34 was [this one](https://github.com/facebook/react-native/issues/37769). And that issue was resolved in [0.72.4](https://github.com/facebook/react-native/releases/tag/v0.72.4) and also ported back to [0.71.13](https://github.com/facebook/react-native/releases/tag/v0.71.13), so I would suspect that any version of 0.71.13+ would also be sufficient, but likely not back to the 0.68.2 version mentioned here, unfortunately.

On the iOS side, an older version of React Native should still work, as long as it can use the newer version of Xcode.

Attempting to use an older version of this module may help in the short term - you could try version `3.1.0` here, as that was the last version before the Android 34 requirement update. We would not recommend this long term, as it will be missing the more recent updates and fixes that have been made, but it is certainly an option to test out your build environment to start, at least.
