### ISSUE TITLE
React Forms not working after installing appcues SDK

### ISSUE THREAD

**Issue by josarcsal** [appcues/appcues-react-native-module#136]
Hi! I recently installed the AppCues SDK on a React Native app and noticed that after installing it some things related to `react-hook-form` have stopped working making the app unusable.

The problem happens on iOS both real devices and simulators.

After the app launch, everything seems to be working fine and the AppCues flow starts correctly and show as configured on the panel except for the Inputs where we use react-hook-form and some functions seems to not work anymore, ex: `watch()`.

The relevant part of our versions are the following:

    "@appcues/react-native": "3.1.9",
    "react": "18.2.0",
    "react-hook-form": "7.49.3",
    "react-native": "0.72.6",
    
Since there's no errors, warnings or traces I can't even start to work on the issue. Do you have any suggestions? Is there any more detail I can provide to help track this down? Thank you!

**Comment by mmaatttt** [comment]
Hi Jose, thanks for reaching out.

This is quite a strange issue and not one we've seen before. There shouldn't be any reason an Appcues flow would interfere with the behaviour of your form inputs.

A couple questions to clarify:

1. Your text inputs only stop working after an Appcues flow is shown? ie I want to confirm that just having the Appcues SDK running isn't causing any issues
2. Does it make a difference if your inputs are already rendered when the Appcues flow is shown? i.e. is It broken in both of these cases:
    1. Form is rendered (and working), Appcues flow shows, Form stops working
    2. Appcues flow shows, navigate to Form, Form isn't working
3. Does the flow that's displayed include any survey blocks (ie text inputs or other form fields)? I'm guessing it's the "Test Mobile 2" flow you've been working on, so "no"?

I've created a barebones test app to try and reproduce the issue: https://github.com/mmaatttt/appcues-react-native-module-issue-136. It uses the [versions you've listed](https://github.com/mmaatttt/appcues-react-native-module-issue-136/blob/3ff22d45991806ccd1b70e3fe246745b06f5b2d5/package.json#L13-L16) and then has a [couple uses of `watch()`](https://github.com/mmaatttt/appcues-react-native-module-issue-136/blob/3ff22d45991806ccd1b70e3fe246745b06f5b2d5/App.tsx#L30-L31) on one `TextInput`. Then I setup Appcues to be able to launch a flow on demand. After all that, the text input still works fine with `watch()`. 

![Simulator Screenshot - iPhone 15 Pro - 2024-01-25 at 16 23 54](https://github.com/appcues/appcues-react-native-module/assets/845681/f03a9af3-adb5-4167-8c0a-0de5cf65ae18)

Could you take a look at the test app and let me know if it looks like it should be an adequate reproduction of your use case?

And I know this might be a big ask, but the best thing to help us debug the issue would be if you could provide minimal sample code (like my app above) that reproduces the issue.

Thanks,
Matt

**Comment by josarcsal** [comment]
Hi Jose, thanks for replying, I really appreciate it.

Answering your questions:

1. Yes it stop working as soon as the Appcues flow shown, before that everything works okey, initializing the session, identifying the user and even tracking the screen but as soon as I reach a screen where the flow is triggered it stop working.

2. The inputs are rendered after the flow is shown, we navigate to a modal which is basically a fullscreen multine input. So is Appcues flow shows, navigate to Form, Form isn't working.

3. I does not includes any survey block that I know of. Is kind of frustrating since we want to implement this for production, we also tried to update to expo 50 an react-native 0.73.2 but nothing seems to be working and it is breaking a main feature of the app.

About providing a sample code I can't assure anything since I'm just a developer so I should ask.

Thanks,
Jose

**Comment by mjd-myob** [comment]
@mmaatttt @josarcsal, we've been seeing similar issues on our project. Did we resolve this?
Can provide more info if needed.

**Comment by mmaatttt** [comment]
@mjd-myob we spent quite a bit of time debugging this, but were not able to come to a satisfying conclusion.

A minimal reproducible example would be most helpful since the issue never surfaced in my test app.

And can you confirm if you're having the same specific problem described in this issue, or it is different in some way?

**Comment by mmaatttt** [comment]
**We've released a fix for this issue in version [4.4.3](https://github.com/appcues/appcues-react-native-module/releases/tag/4.4.3).**

We discovered that:
1. When an Appcues flow enters an error recovery state (trying to find a tooltip target) on iOS,
2. Any new multi line `TextInput` component would fail to call it's `onChangeText` handler,
3. Because our step recovery implementation was setting a `UIScrollView` delegate and [this](https://github.com/facebook/react-native/blob/f53d066d26352e6abfdf2f727ea06425ea163039/packages/react-native/Libraries/Text/TextInput/Multiline/RCTUITextView.mm#L69) internal React Native check would fail

This would impact usages with `react-hook-form` as well as local `useState` hooks.
