### ISSUE TITLE
App hanging in AppcuesHostingController.init

### ISSUE THREAD

**Issue by jp1987** [appcues/appcues-react-native-module#161]
This was on an iPhone SE (2nd gen), see Sentry issue [here](https://bereik.sentry.io/share/issue/1e31a817d50546beb7528a87aece02be/), more details are available on request.

**Comment by mmaatttt** [comment]
Hi @jp1987, thanks for the detailed report link. The report tells us the issue is with starting the presentation of a flow, but not any more information than that, so I'd like to start with investigating the flow itself.

Can you confirm what SDK version the affected device was using and share the flow name or ID for me to lookup? You're welcome to email me at matt.hayashida@appcues.com if you'd prefer.

**Comment by jp1987** [comment]
Thanks @mmaatttt, closing this & and continuing via mail due to some sensitive data.
