### ISSUE TITLE
Android: star rating widget selected state color not appearing

### ISSUE THREAD

**Issue by mikrich** [appcues/appcues-react-native-module#164]
We have implemented a star rating widget with the following configuration:
![Screenshot 2024-09-26 at 4 17 23 PM](https://github.com/user-attachments/assets/eade6309-e9fb-4272-8cc0-8ebe23120474)

This works as expected on iOS however on Anrdoid (simulator and physical device) when the user taps the star the selected state color does not appear. The rating is recorded however the user does no see this and it appears if nothing has happened.

I've reproduced this on version `4.0.0` and also on `3.2.0`. Please let me know if I can provide any additional info

**Comment by iujames** [comment]
Hi @mikrich , thanks for reaching out. I've taken a look at this issue here and attempted to reproduce in both a native Android test app, and a React Native Android test app. I am using the `4.0.0` version of the SDK. So far I have not been able to reproduce, as the tapped stars are showing the selected rating.

![Screenshot 2024-09-26 at 11 43 05 AM](https://github.com/user-attachments/assets/dd310725-a68b-4070-ab7a-423be758963c)

There may be something different about how I am testing from the configuration you are using, though. At this point, I'd recommend emailing in to support@appcues.com or filling out a contact form at https://docs.appcues.com/contact-us. This way we can gather more details about your account and the flow you are using, and do a deeper inspection to see if there are any issues in how this flow is set up or the SDK is interpreting it.

Thanks for using Appcues, and if you have any more details you'd like to share right here in the meantime, please feel free. I'll keep this open and monitor it.

**Comment by mikrich** [comment]
Thanks for getting back to me. It seems like re-creating the flow has fixed the issue for now, will keep an eye our for it and let you know if it happens again.
